### ISSUE TITLE
로그인 & 회원가입 페이지 구현

### ISSUE THREAD

**Issue by ph0109** [6ITAll/book-it-da#23]
## 어떤 기능인가요?
<img width="528" alt="스크린샷 2024-12-16 오후 9 57 40" src="https://github.com/user-attachments/assets/8e37a52b-520e-4eae-9962-6b419acff997" />

- 사용자가 아이디와 비밀번호를 통해 로그인
- 새로운 계정을 생성할 수 있는 회원가입 

## 작업 상세 내용

- [x] API와 연동하여 로그인 요청 전송 기능 구현
- [x] API와 연동하여 회원가입 요청 전송 기능 구현
- [x] 데이터 유효성 검사

## 질문
- 유효성 검사를 위한 라이브러리 
- 전에 종혁님의 와이어프레임 보고 만들긴 했는데 은지님이 디스코드에 보내주신 것처럼 깔끔하게 할지 고민됩니다.

**Comment by publdaze** [comment]
저는 유효성 검사 관련해서 폼데이터 처리 쉽게할 수 있는 react hook form 라이브러리 사용해봤는데 괜찮았습니다!

**Comment by publdaze** [comment]
> 전에 종혁님의 와이어프레임 보고 만들긴 했는데 은지님이 디스코드에 보내주신 것처럼 깔끔하게 할지 고민됩니다.

깔끔하게 할 지 고민되는 부분이 좌측 배너? 여부에 대한 걸까요? 아니면 폼 요소 구성 or 배치에 대한 부분일까요?

**Comment by deenuit113** [comment]
> 저는 유효성 검사 관련해서 폼데이터 처리 쉽게할 수 있는 react hook form 라이브러리 사용해봤는데 괜찮았습니다!
yup 과 같이 사용하면 이메일과 비밀번호 입력 양식을 정규표현식으로 쉽게 관리할 수 있어서 좋습니다! 추천드려요~

**Comment by deenuit113** [comment]
SNS 로그인 기능 구현 고려중이신지도 궁금합니다!
