### ISSUE TITLE
책 검색 페이지 개발

### ISSUE THREAD

**Issue by Hyunsangs** [6ITAll/book-it-da#25]
## 어떤 기능인가요?

책 검색 페이지 개발
![스크린샷 2024-12-16 오후 7 34 01](https://github.com/user-attachments/assets/2d91eec1-3a87-480e-8956-efd46e3fdec9)
![image](https://github.com/user-attachments/assets/ff557687-f2c5-4534-b852-0448951058d0)

### 상단 베스트 셀러 부분

- 슬라이딩 형식으로 움직이며  베스트 셀러책을 보여 줌
- 날짜별 베스트 셀러까지 된다면 올해 월 기준

### 카테고리바

- 책의 카테고리를 삽입
- 근데 너무,,많기도하고 없는게 낫다면 빼는게 나을까요? 

### 검색바

- 도서 제목, 저자, 가격, 출판일, 출판사 기준으로 검색 가능

### 책 컴포넌트 부분

- 카테고리 혹은 검색의 맞게 책들이 보이는 곳
- 은지님이 보내주신 ui로 제작할 것 같음.

## 작업 상세 내용

- [ ] 알라딘 api 구현 
- [ ] 검색 기능 구현( 카테고리, 도서 명 등등)
- [ ] 책 컴포넌트 구현
- [ ] 카테고리별 책 찾기

## 질문사항
- 은지님이 보내주신 ui가 괜찮은거 같아서 전체적인 것은 은지님 사진위주로 하고 베스트셀러따로 저렇게 위에 보이게 하는게 어떤지 의견 말해주시면 감사하겠습니다.
- 검색후 책 카드요소들을 어떻게 배치할지가 고민이네요.. 은지님이 보내주신 것으로 생각 하고 있습니다.

**Comment by deenuit113** [comment]
### 베스트셀러 위에 보이게 하는 것은 좋은 것 같습니다!
- 다만 알라딘에서 주 단위로 제공하는 것 같아서 월 단위로는 안될 것 같습니다...
![image](https://github.com/user-attachments/assets/d2f358de-aafc-437e-a25c-aaf4bcbf1c43)
 
### 베스트셀러 말고도 다른 다양한 방식으로도 도서들을 추천하는 것 같습니다!
- 버튼 컨트롤이나 캐러셀로 신간이나 편집자 추천 도서들도 볼 수 있게 해도 좋을 것 같습니다~
![image](https://github.com/user-attachments/assets/556c0a0d-8c6e-4dab-a44f-4294c1f320e9)

### 저도 은지님이 올려주신 사진이 더 간단하고 깔끔해보이는 것 같습니다!
- 카테고리 바 대신 은지님이 만들어주신 사진 안에 있는 것처럼 태그를 이용하는 게 현상님께도 덜 번거로울 것 같습니다~
- 추가로 별점 옆에 몇 명이 평가했는지 넣어줘도 좋을 것 같습니다!
  - 예) ★4.5 (23)

**Comment by Hyunsangs** [comment]
상세한 피드백 감사합니다.
